CREATE TABLE IF NOT EXISTS patient (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    persoon_id INT UNSIGNED NOT NULL,
    nummer VARCHAR(255) NOT NULL,
    medisch_dossier TEXT NULL,
    straatnaam VARCHAR(255) NOT NULL,
    huisnummer SMALLINT NOT NULL,
    toevoeging VARCHAR(10) NULL,
    postcode VARCHAR(10) NOT NULL,
    plaats VARCHAR(100) NOT NULL,
    mobiel VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    is_active BIT NOT NULL DEFAULT 1,
    comments VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_persoon FOREIGN KEY (persoon_id) REFERENCES persoon(id) ON DELETE CASCADE
) ENGINE=InnoDB;