CREATE TABLE IF NOT EXISTS patient (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PersoonId INT UNSIGNED NOT NULL UNIQUE,
    Nummer VARCHAR(255) NOT NULL,
    MedischDossier TEXT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    Comments VARCHAR(255) NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
