 CREATE TABLE IF NOT EXISTS persoon (
        Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        VolledigeNaam VARCHAR(150),
        Geboortedatum DATE NOT NULL,
        IsActive BIT DEFAULT 1,
        Comments VARCHAR(255) NULL,
        CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB;


