DROP PROCEDURE IF EXISTS create_gebruiker_table;

CREATE PROCEDURE create_gebruiker_table()
BEGIN
    CREATE TABLE IF NOT EXISTS gebruiker (
        Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        PersoonId INT UNSIGNED NOT NULL,
        Gebruikersnaam VARCHAR(255) NOT NULL,
        Wachtwoord VARCHAR(255) NOT NULL,
        Isingelogd BIT DEFAULT 0 NOT NULL,
        Ingelogd TIMESTAMP(6) NULL DEFAULT NULL,
        Uitgelogd TIMESTAMP(6) NULL DEFAULT NULL,
        IsActive BIT DEFAULT 1 NOT NULL,
        Comments VARCHAR(255) NULL,
        CreatedAt TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
        UpdatedAt TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        FOREIGN KEY (PersoonId) REFERENCES persoon(Id) ON DELETE CASCADE ON UPDATE CASCADE
    ) ENGINE=InnoDB;
END;