CREATE PROCEDURE IF NOT EXISTS create_patient_table()
BEGIN
    CREATE TABLE IF NOT EXISTS patienten (
        Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
        ,PersoonId INT UNSIGNED NULL
        ,Nummer VARCHAR(255) NOT NULL                
        ,MedischDossier TEXT NULL  
        ,IsActive BIT DEFAULT 1
        ,Comments VARCHAR(255) NULL
        ,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ,UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );
END;