DROP PROCEDURE IF EXISTS create_rol_table;

CREATE PROCEDURE create_rol_table()
BEGIN
    CREATE TABLE IF NOT EXISTS rol (
        Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        GebruikerId BIGINT UNSIGNED NOT NULL,
        Naam VARCHAR(255) NOT NULL,
        IsActive BIT DEFAULT 1,
        Comments VARCHAR(255) NULL,
        CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (gebruikerId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
    ) ENGINE=InnoDB;
END;
